version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run: pip3 install twine
      - run: echo "$CIRCLE_TAG" > VERSION.txt
      - run: twine upload -u "python-efficiency" -p "$PYPI_PASSWORD" "dist/*"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
